### PR TITLE
Red theme for attendance below 75%

### PR DESCRIPTION
**Pull request by ayushgx**

### CODE REVIEW

**Comment by xpt1x** [comment]
I guess its not necessary as, the color code is automatically generated through backed Green or red, if not then please reply again

**Comment by ayushgx** [comment]
> I guess its not necessary as, the color code is automatically generated through backed Green or red, if not then please reply again

Then I think it is not working as I'm having 50% attendence in one sub and it's still green

**Comment by xpt1x** [comment]
@ayushgx please check response from API in network tab and share results

**Comment by xpt1x** [comment]
Thanks @ayushgx 
Seem like there no use of colorcode for attendance display, added percentage check logic

**Pull request closed without merging**
